name: Build & Test
'on':
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v1
        with:
          java-version: '${{ matrix.java }}'
      - name: Execute OAuth
        run: mvn clean install -Dspring.profiles.active=oauth
      - name: Execute MTSL
        run: mvn clean install -Dspring.profiles.active=mtls

